//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CAppGraph.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("B2CAppGraph.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;displayName&quot;: &quot;#appName#&quot;,
        ///    &quot;isFallbackPublicClient&quot;: false,
        ///    &quot;web&quot;: {
        ///        &quot;redirectUris&quot;: [
        ///            &quot;https://jwt.ms&quot;
        ///        ],
        ///		 &quot;implicitGrantSettings&quot;: {
        ///                    &quot;enableIdTokenIssuance&quot;: false,
        ///                    &quot;enableAccessTokenIssuance&quot;: true
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string appTemplate {
            get {
                return ResourceManager.GetString("appTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;clientId&quot;: &quot;#spId#&quot;,
        ///&quot;consentType&quot;: &quot;AllPrincipals&quot;,
        ///&quot;principalId&quot;: null,
        ///&quot;expiryTime&quot;: &quot;2019-06-09T00:07:10.7595352Z&quot;,
        ///&quot;resourceId&quot;: &quot;#MSGraphSPID#&quot;,
        ///&quot;scope&quot;: &quot; openid offline_access&quot;
        ///}
        ///
        ///
        ///.
        /// </summary>
        internal static string oAuthPermissionGrantsTemplate {
            get {
                return ResourceManager.GetString("oAuthPermissionGrantsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;accountEnabled&quot;: true,
        ///&quot;appId&quot;: &quot;#appId#&quot;,
        ///&quot;appRoleAssignmentRequired&quot;: false
        ///}.
        /// </summary>
        internal static string servicePrincipalTemplate {
            get {
                return ResourceManager.GetString("servicePrincipalTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;web&quot;: {
        ///  &quot;implicitGrantSettings&quot;: {
        ///            &quot;enableIdTokenIssuance&quot;: false,
        ///            &quot;enableAccessTokenIssuance&quot;: true
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string updateAppTemplate {
            get {
                return ResourceManager.GetString("updateAppTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///            
        ///           &quot;availableToOtherTenants&quot;: true,
        ///            &quot;displayName&quot;: &quot;#appName#&quot;,
        ///            &quot;oauth2AllowIdTokenImplicitFlow&quot;: true,
        ///            &quot;oauth2AllowImplicitFlow&quot;: true,
        ///            &quot;oauth2AllowUrlPathMatching&quot;: false
        ///			&quot;replyUrls&quot;: [
        ///				&quot;https://jwt.ms&quot;
        ///			]
        /// }.
        /// </summary>
        internal static string v1AppTemplate {
            get {
                return ResourceManager.GetString("v1AppTemplate", resourceCulture);
            }
        }
    }
}
